language: rust
dist: bionic

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - sudo apt-get update
  - sudo apt-get install php composer
  - php --version
  - composer --version
