language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - sudo apt-get update
  - sudo apt-get install php
  - php --version
